export const PERMISOS = {
  BUSCAR_ARCHIVO: "BUSCAR_ARCHIVO",
  CREAR_EXPEDIENTE: "CREAR_EXPEDIENTE",
  ACTUALIZAR_ARCHIVO: "ACTUALIZAR_ARCHIVO",
  ELIMINAR_ARCHIVO: "ELIMINAR_ARCHIVO",
  ADMINISTRAR_USUARIOS: "ADMINISTRAR_USUARIOS",
  ARCHIVAR_DOCUMENTO: "ARCHIVAR_DOCUMENTO",
  RESTAURAR_DOCUMENTO: "RESTAURAR_DOCUMENTO",
};